# Solving Systems of Linear Equations with NumPy - Lab

## Introduction 

Now we have gathered all the required skills needed to solve systems of linear equations. We saw why need to calculate inverses of matrices, followed by matrix multiplication to figure the values of unknown variables. 

Following exercises present some problems that can be converted into a system of linear equations. Solve the problems for the values of unknown variables. 

## Objectives
You will be able to:

* Build a system of equations from given problem by creating matrix and vectors in NumPy
* Calculate the inverse and dot-product to get the values for unknown variables.
* Solve linear equations using `numpy.linalg.solve()`

## Exercise 1

A coffee shop is having a sale on coffee and tea. 

On day 1, 29 bags of coffee and 41 bags of tea was sold, giving a total of 490 dollars.

On day 2, they sold 23 bags of coffee and 41 bags of tea, for which customers paid a total of 448 dollars.  

How much does each bag cost?

In [2]:
import numpy as np

In [7]:
# Solution:
A = np.matrix([[29,41],[23,41]])
B = np.matrix([490,448])

A_inv = np.linalg.inv(A)
B = B.T

X = A_inv.dot(B)
print(X)

np.linalg.solve(A,B)

[[7.]
 [7.]]


matrix([[7.],
        [7.]])

In [8]:
# Explain your answer in terms of prices
# Each bag of coffee costs 7 dollars, and each bag of tea costs 7 dollars. These values satisfy total for each day.

## Exercise 2:

The cost of admission to a popular music concert was 162 dollars for 12 children and 3 adults. 

The admission was 122 dollars for 8 children and 3 adults in another music concert. 

How much was the admission for each child and adult?

In [10]:
# Create a system of equations
C = np.matrix([[12,3],[3,8]])
D = np.matrix([162,122])

np.linalg.solve(C,D.T)

matrix([[10.68965517],
        [11.24137931]])

In [11]:
# Describe your result
# The cost per child was $11.24, and the cost per adult was $10.69.

## Exercise 3:

You want to make a certain kind of tropical punch, using bananas, oranges, and papayas. 

Suppose you don't know how many of each to put in the punch, but you know that there are seven pieces of fruit in the mix, and there are twice as many oranges as bananas. 

You also know that the seven pieces of fruit cost \$5.25, 

where bananas cost \$.50 each, oranges cost \$.75 each, and papayas cost \$1.25 each.

How many bananas, oranges and papayas would you need to make this punch ?

In [12]:
# Create a system of equations
E = np.matrix([[2,1.25],[3,1]])
F = np.matrix([5.25,7])

np.linalg.solve(E,F.T)

matrix([[2.],
        [1.]])

In [13]:
# Explain your answer
# 2 bananas, 4 oranges, and 1 papaya is needed to make this punch. The values for bananas and oranges were combined
# because their relationship is constant. Any increase in the amount of banana would increase total price by $2.00.
# Any increase in the amount of banana would increase total fruit count by 3. This resulted in a 2x2 matrix which was
# used to solve the linear equation. The results were 2 sets of banana/orange, which came out to be 2 bananas and 4
# oranges, and 1 papaya.

## Exercise 4

A landlord owns 3 houses, a 1-bedroom, a 2-bedroom , and a 3-bedroom house. 

The total rent he receives is 1240 dollars. 

He needs to make some repairs, where it costs 10% of the 1-bedroom house’s rent for its repairs, 20% of the 2-bedroom for its repairs, and 30% of the 3-bedroom house's rent for its repairs.  The total repair bill for all three houses was $276. 

The 3-bedroom house's rent is twice the 1-bedroom house’s rent. 

How much is the individual rent for three houses?

In [14]:
# Create a system of equations
G = np.matrix([[3,1],[0.7,0.2]])
H = np.matrix([1240,276])

np.linalg.solve(G,H.T)

matrix([[280.],
        [400.]])

In [11]:
# Explain your answer
# The 1-bedroom rent is 280 dollars, the 2-bedroom rent is 400 dollars, and the 3-bedroom rent is 560 dollars, for a
# total of 1240 dollars. The 1-bedroom and 3-bedroom values were combined because of their constant relationship. The
# first row of G was set 

## Summary
In this lab, we saw how to use Numpy to solve linear equations by taking inverses and matrix multiplication and also using numpy's `.solve()`. We shall now take these skills forward and see how we can define a simple regression problem using linear algebra and solve it with numpy, only using the skills that we have learnt so far. 